MojePrvniWebovaAplikace/Controllers/BooksController.cs
using DataAccess.Model;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Web;
using System.Web.Mvc;
using DataAccess.Dao;
using MojePrvniWebovaAplikace.Class;

namespace MojePrvniWebovaAplikace.Controllers
{
    
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Index()
        {
            ViewBag.Datum = DateTime.Now.ToShortDateString();

            BookDao bookDao = new BookDao();
            IList<Book> books = bookDao.GetAll();
            return View(books);
        }
        //Otazníkem (v případě Booleanu v metodě níže) se označuje parametr, jako "nullable", tedy nemusí se zadávat během volání tohoto pohledu a může být prázdný "null".
        public ActionResult Detail(int id)
        {
            BookDao bookDao = new BookDao();
            Book b = bookDao.GetById(id);
           

            return View(b);
        }
     
    }

    }
    

MojePrvniWebovaAplikace/Controllers/VlastniController.cs
using System.Web.Mvc;

namespace MojePrvniWebovaAplikace.Controllers
{
    
    public class VlastniController : Controller
    {
        // GET: Vlastni
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cas()
        {
            return View();
        }
        public ActionResult NahodneCislo()
        {
            return View();
        }

    }
}

MojePrvniWebovaAplikace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Moje stránka</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/VlastniStyly.css")" rel="stylesheet">
</head>
<body>
    <header>
        <h1>Knihovna</h1>
    </header>
    <nav>
        <ul class="nav">
            <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index", "Home")">Home</a></li>
            <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index","Books")">Výpis knih</a></li>
            <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index", "Vlastni" )">Vlastní index</a></li>
            <li class="nav-item"><a class="nav-link active" href="@Url.Action("Cas", "Vlastni" )">Aktuální datum a čas</a></li>
            <li class="nav-item"><a class="nav-link active" href="@Url.Action("NahodneCislo", "Vlastni" )">Náhodné číslo</a></li>
            <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index","Login", new{area="Admin"})">Přihlášení</a></li>
        </ul>
    </nav>
<main>
    <div class="container-fluid">
        @if (TempData["message-success"] != null)
        {
            <div class="alert alert-success alert-dismissible fade" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Zavřít"><span aria-hidden="true"></span></button>
                @TempData["message-success"]
            </div>
        }

        @RenderBody()
    </div>
</main>
<aside>
<div class="container-fluid mt-3" id="sidebar">
    @RenderSection("sidebar",false)
</div>
</aside>
    <script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
    

</body>
</html>