MojePrvniWebovaAplikace/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Dao;
using DataAccess.Model;

namespace MojePrvniWebovaAplikace.Areas.Admin.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {
        [ChildActionOnly]
        // GET: Admin/Menu
        public ActionResult Index()
        {

            KnihovnaUserDao knihovnaUserDao = new KnihovnaUserDao();
            KnihovnaUser user = knihovnaUserDao.GetByLogin(User.Identity.Name);

            return View(user);
        }
    }
}

MojePrvniWebovaAplikace/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Moje stránka</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/VlastniStyly.css")" rel="stylesheet">
</head>
<body>
    <header>
        <h1>Knihovna</h1>
    </header>
    <nav>
        <ul class="nav">
            @{ Html.RenderAction("Index", "Menu"); }
        </ul>
    </nav>
<main>
    <div class="container-fluid">
        @if (TempData["message-success"] != null)
        {
            <div class="alert alert-success alert-dismissible fade" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Zavřít"><span aria-hidden="true"></span></button>
                @TempData["message-success"]
            </div>
        }

        @RenderBody()
    </div>
    <div class="container-fluid mt-3" id="sidebar">
        @RenderSection("sidebar", false)
    </div>
</main>
    <script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>


</body>
</html>